SCREEN_WIDTH = 480
SCREEN_HEIGHT = 270
PLAYING_AREA_WIDTH = 202
PLAYING_AREA_HEIGHT = SCREEN_HEIGHT

PLAYER_HEIGHT = 32
PLAYER_WIDTH = 16
PLAYER_STARTING_POSITION = vec(SCREEN_WIDTH / 2 - PLAYER_WIDTH / 2, SCREEN_HEIGHT - PLAYER_HEIGHT)
PLAYER_SPRITE_INDEX_OFFSET = 8
